pipeline:
  clone:
    image: plugins/git
    depth: 10
    recursive: true

  docker-build:
    image: docker:18
    commands:
      - docker build --tag skg/ci-tools .
    environment:
      - DOCKER_HOST=tcp://localhost:2375

services:
  docker:
    image: docker:18-dind
    privileged: true
    command: [ "--storage-driver=overlay"]
